version: "3.8"

volumes:
  mysql_data: {}

services:
  Backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    image: gregvader/backend:latest
    volumes:
      - mysql_data:/var/lib/mysql/data
    expose: 
      - "80"
    ports:
      - "5100:80"

  IntegrationAdapter:
    build: 
      context: ./IntegrationAdapter
      dockerfile: Dockerfile
    image: gregvader/integrationadapter:latest
    #depends-on: 
    #  - Backend
    expose: 
      - "80"
    ports:
      - "5101:80"

  WebApplication:
    build: 
      context: ./WebApplication
      dockerfile: Dockerfile
    image: gregvader/webapplication:latest
    #depends-on: 
    #  - Backend
    expose: 
      - "80"
    ports:
      - "5102:80"

  WebApplicationFront:
    build:
      context: ./web-application-front 
      dockerfile: Dockerfile
    image: gregvader/webapplication:latest

  IntegrationAdapterTests:
    build:
      context: ./IntegrationAdapterTests 
      dockerfile: Dockerfile
    image: gregvader/integrationadaptertests:latest
    expose: 
      - "80"
    ports: 
      - "5103:80"

  WebApplicationTests:
    build:
      context: ./WebApplicationTests 
      dockerfile: Dockerfile
    image: gregvader/webapplicationtests:latest
    expose: 
      - "80"
    ports: 
      - "5104:80"

