version: "3.8"

volumes:
  mysql_data: {}

services:
  Backend:
    build: 
      context: .
      dockerfile: Backend/Dockerfile
    image: gregvader/backend:latest
    volumes:
      - mysql_data:/var/lib/mysql/data
    expose: 
      - "80"
    ports:
      - "5100:80"

  IntegrationAdapter:
    build: 
      context: .
      dockerfile: IntegrationAdapter/Dockerfile
    image: gregvader/integrationadapter:latest
    depends_on: 
      - Backend
    expose: 
      - "80"
    ports:
      - "5101:80"

  WebApplication:
    build: 
      context: .
      dockerfile: WebApplication/Dockerfile
    image: gregvader/webapplication:latest
    depends_on:
      - Backend
    expose: 
      - "80"
    ports:
      - "5102:80"

  WebApplicationFront:
    build:
      context: .
      dockerfile: web-application-front/Dockerfile
    image: gregvader/webapplication:latest
    depends_on:
      - WebApplicationTests

  IntegrationAdapterTests:
    build:
      context: . 
      dockerfile: IntegrationAdapterTestsDockerfile
    image: gregvader/integrationadaptertests:latest
    depends_on:
      - IntegrationAdapter
    expose: 
      - "80"
    ports: 
      - "5103:80"

  WebApplicationTests:
    build:
      context: . 
      dockerfile: WebApplicationTests/Dockerfile
    image: gregvader/webapplicationtests:latest
    depends_on:
      - WebApplication
    expose: 
      - "80"
    ports: 
      - "5104:80"

